import {
  Column,
  Entity,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { numericTransformer } from '../common/numeric.transformer';
import { WorkoutEntry } from './workout-entry.entity';

/**
 * A single set within a workout entry.
 *
 * Weight is stored twice by design:
 * - weight_original + unit_original: exactly what the user logged
 * - weight_kg: normalized by the app at insert (conversion factors live
 *   in the unit registry, not the DB)
 *
 * volume_kg and est_1rm_kg are DB-generated STORED columns — the formula
 * lives in one place (the migration), values can never drift from
 * reps/weight_kg, and PR queries become plain MAX() over stored columns.
 */
@Entity('sets')
export class WorkoutSet {
  @PrimaryGeneratedColumn({ type: 'bigint' })
  id: string;

  @Column({ type: 'uuid', name: 'entry_id' })
  entryId: string;

  @ManyToOne(() => WorkoutEntry, (entry) => entry.sets, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'entry_id' })
  entry: WorkoutEntry;

  /** 1-based order of the set within its entry. */
  @Column({ type: 'int' })
  position: number;

  @Column({ type: 'int' })
  reps: number;

  @Column({
    type: 'numeric',
    precision: 8,
    scale: 3,
    name: 'weight_original',
    transformer: numericTransformer,
  })
  weightOriginal: number;

  @Column({ type: 'text', name: 'unit_original' })
  unitOriginal: string;

  @Column({
    type: 'numeric',
    precision: 8,
    scale: 3,
    name: 'weight_kg',
    transformer: numericTransformer,
  })
  weightKg: number;

  /** reps * weight_kg — generated by the DB, read-only from the app. */
  @Column({
    type: 'numeric',
    precision: 12,
    scale: 3,
    name: 'volume_kg',
    insert: false,
    update: false,
    transformer: numericTransformer,
  })
  volumeKg: number;

  /** Epley 1RM: weight_kg * (1 + reps/30) — generated by the DB. */
  @Column({
    type: 'numeric',
    precision: 12,
    scale: 3,
    name: 'est_1rm_kg',
    insert: false,
    update: false,
    transformer: numericTransformer,
  })
  est1RmKg: number;
}
