import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema: exercises catalog, workout entries, sets.
 *
 * Hand-written SQL (not autogenerated) because the expression index,
 * generated columns, and CHECK constraints are the core of the design:
 * - LOWER(name) unique index → case-insensitive exercise identity
 * - (user_id, exercise_id, workout_date DESC) → PR + per-exercise history
 * - (user_id, workout_date DESC, id DESC) → keyset pagination, matches
 *   ORDER BY exactly so pages read straight off the index without sorting
 * - volume_kg / est_1rm_kg GENERATED STORED → PR queries are indexed MAX()
 *   with the formulas defined in exactly one place
 */
export class InitialSchema1782988851000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE exercises (
        id           SERIAL PRIMARY KEY,
        name         TEXT NOT NULL,
        muscle_group TEXT NOT NULL,
        created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`
      CREATE UNIQUE INDEX ux_exercises_name_lower
        ON exercises (LOWER(name))
    `);

    await queryRunner.query(`
      CREATE TABLE workout_entries (
        id           UUID PRIMARY KEY,
        user_id      TEXT NOT NULL,
        exercise_id  INT NOT NULL REFERENCES exercises (id),
        workout_date DATE NOT NULL,
        logged_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await queryRunner.query(`
      CREATE INDEX ix_entries_user_exercise_date
        ON workout_entries (user_id, exercise_id, workout_date DESC)
    `);
    await queryRunner.query(`
      CREATE INDEX ix_entries_user_date_id
        ON workout_entries (user_id, workout_date DESC, id DESC)
    `);

    await queryRunner.query(`
      CREATE TABLE sets (
        id              BIGSERIAL PRIMARY KEY,
        entry_id        UUID NOT NULL REFERENCES workout_entries (id) ON DELETE CASCADE,
        position        INT NOT NULL,
        reps            INT NOT NULL,
        weight_original NUMERIC(8,3) NOT NULL,
        unit_original   TEXT NOT NULL,
        weight_kg       NUMERIC(8,3) NOT NULL,
        volume_kg       NUMERIC(12,3) GENERATED ALWAYS AS (reps * weight_kg) STORED,
        est_1rm_kg      NUMERIC(12,3) GENERATED ALWAYS AS (weight_kg * (1 + reps / 30.0)) STORED,
        CONSTRAINT chk_sets_position_positive CHECK (position > 0),
        CONSTRAINT chk_sets_reps_positive CHECK (reps > 0),
        CONSTRAINT chk_sets_weight_original_non_negative CHECK (weight_original >= 0),
        CONSTRAINT chk_sets_weight_kg_non_negative CHECK (weight_kg >= 0)
      )
    `);
    await queryRunner.query(`
      CREATE INDEX ix_sets_entry ON sets (entry_id)
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE sets`);
    await queryRunner.query(`DROP TABLE workout_entries`);
    await queryRunner.query(`DROP TABLE exercises`);
  }
}
